# Generated by Django 3.1 on 2020-08-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_auto_20200816_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата ремонта')),
                ('speedometer', models.FloatField(blank=True, null=True, verbose_name='Спидометр')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='JournalReplacements',
        ),
    ]
