# Generated by Django 3.1 on 2020-08-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_journal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='user_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.userservice', verbose_name='Автовладелец'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.journal', verbose_name='Событие')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.routinemaintenance', verbose_name='Работа')),
            ],
        ),
        migrations.CreateModel(
            name='Replacments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.details', verbose_name='Деталь')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.journal', verbose_name='Событие')),
            ],
        ),
    ]
