# Generated by Django 3.1 on 2020-08-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cars', '0006_auto_20200816_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='speedometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спидометр'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.userservice', verbose_name='Автовладелец'),
        ),
        migrations.AlterField(
            model_name='partsresource',
            name='resource',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='resource',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ресурс'),
        ),
    ]
