# Generated by Django 3.1 on 2021-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_auto_20200816_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user_car',
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
    ]
