# Generated by Django 3.1 on 2021-02-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0009_auto_20210223_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkaCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(db_index=True, max_length=20, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марки автомобилей',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['-marka'],
            },
        ),
        migrations.CreateModel(
            name='ModelCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=20, verbose_name='Модель')),
                ('marka_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.markacars', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модели автомобилей',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['-model'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(db_index=True, max_length=20, verbose_name='Автомобиль')),
                ('reg_number', models.CharField(db_index=True, max_length=20, verbose_name='Гос.Номер')),
                ('marka_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.markacars', verbose_name='Марка')),
                ('model_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.modelcars', verbose_name='Модель')),
                ('user_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.userservice', verbose_name='Автовладелец')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-name_car'],
            },
        ),
    ]
