# Generated by Django 3.1 on 2021-02-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0010_cars_markacars_modelcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата ремонта')),
                ('type_event', models.SmallIntegerField(choices=[(1, 'Начало эксплуатации'), (2, 'Ремонт'), (3, 'Сверка спидометра')], default=3)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('speedometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Спидометр')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
                'ordering': ['-date'],
            },
        ),
    ]
