# Generated by Django 3.1 on 2021-02-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0011_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrReplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.journal', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Журнал - записи',
                'verbose_name_plural': 'Журнал - записи',
            },
        ),
    ]
