# Generated by Django 3.1 on 2021-02-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_workorreplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_detail', models.CharField(db_index=True, max_length=20, verbose_name='Деталь/Работа')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Деталь/Работа',
                'verbose_name_plural': 'Деталь/Работа',
                'ordering': ['-name_detail'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ресурс')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.cars', verbose_name='Автомобиль')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.details', verbose_name='Деталь/Работа')),
            ],
            options={
                'verbose_name': 'ресурс деталей',
                'verbose_name_plural': 'ресурс деталей',
            },
        ),
    ]
