# Generated by Django 3.1 on 2021-02-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0013_details_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorreplace',
            name='datail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cars.details', verbose_name='Работа/Деталь'),
        ),
        migrations.AlterField(
            model_name='workorreplace',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cars.journal', verbose_name='Событие'),
        ),
    ]
