# Generated by Django 3.1 on 2021-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0014_auto_20210225_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name_detail',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Деталь/Работа'),
        ),
    ]
