# Generated by Django 3.1 on 2021-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0015_auto_20210225_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'ordering': ['-detail'], 'verbose_name': 'ресурс деталей', 'verbose_name_plural': 'ресурс деталей'},
        ),
        migrations.AddField(
            model_name='resources',
            name='last_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата ремонта'),
        ),
    ]
