# Generated by Django 3.1 on 2021-02-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0017_resources_planned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='sm_work',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спидометр'),
        ),
    ]
