# Generated by Django 3.1 on 2021-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0018_resources_sm_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
